version: '3.3'

services:
  compiler_service:
    env_file:
      -  .env 
    image: $COMPILER_SERVICE_NAME
    build: $COMPILER_SERVICE_BUILD
    container_name: $COMPILER_SERVICE_NAME
    ports: 
      - $COMPILER_SERVICE_EXPOSE_PORT:$COMPILER_SERVICE_PORT
    expose: 
      - $COMPILER_SERVICE_EXPOSE_PORT
    environment:
      PORT: $COMPILER_SERVICE_PORT
      UPLOADS_PATH: $COMPILER_UPLOADS_PATH 
      COMPILE_AND_EXECUTE_COMMAND_JS: $COMPILE_AND_EXECUTE_COMMAND_JS
      COMPILE_AND_EXECUTE_COMMAND_JAVA: $COMPILE_AND_EXECUTE_COMMAND_JAVA
      COMPILE_AND_EXECUTE_COMMAND_CS: $COMPILE_AND_EXECUTE_COMMAND_CS
      COMPILE_AND_EXECUTE_COMMAND_PYTHON: $COMPILE_AND_EXECUTE_COMMAND_PYTHON
    restart: always     